apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: demo-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - hostPort: 30000
    containerPort: 30000
    protocol: TCP
  - hostPort: 39090
    containerPort: 39090
    protocol: TCP
  - hostPort: 30080
    containerPort: 30080
    protocol: TCP
  - hostPort: 30443
    containerPort: 30443
    protocol: TCP
  - hostPort: 36686
    containerPort: 36686
    protocol: TCP  
  - hostPort: 30200
    containerPort: 30200
    protocol: TCP         