apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: monitoring
data:
  nginx.conf: |
    events {
      worker_connections 768;
      # multi_accept on;
    }

    http {  
      server {
        listen 80;
        root /usr/share/nginx/www;
        index index.html index.htm;

        location / {
        proxy_pass http://grafana.monitoring:3000/;
        proxy_set_header Host $http_host;
        }
      }
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: log
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30105
  selector:
    app: nginx